create database customer_behaviour;
use customer_behaviour;
select * from customer limit 20;
# Business Questions:

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT 
    gender, SUM(purchase_amount) as total_revenue_in_USD
FROM
    customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'YES'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS 'Average Product Rating'
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT shipping_type, AVG(purchase_amount) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and  non-subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customer,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS average_spend
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , average_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    CONCAT(
        ROUND(
            SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END) 
            * 100.0 / COUNT(*),
        2),
        '%'
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY 
    SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END) 
    * 100.0 / COUNT(*) DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1  then "New"
    when previous_purchases between 2 AND 10  then "Returning"
	else "Loyal"
    end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- We can also calculate the segment directly inside the GROUP BY. 

SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS number_of_customers
FROM customer
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 

SELECT category, item_purchased, purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE rank_in_category <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyer
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 

SELECT 
    age_group, SUM(purchase_amount) AS revenue_contribution
FROM
    customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;
